
### Présentation des données
fichier eco2mix : contient les données de la consommation éléctrique en France.
Cela comporte la consommation, la production, échanges commerciaux d'électricité, émission de CO2, 

## Questions 


# Load the data

Dataset source : https://www.rte-france.com/eco2mix/telecharger-les-indicateurs

```{r}
# load data.csv file
# row_data <- read.csv("courbe-de-charge-de-la-production-delectricite-par-filiere.csv", header = TRUE, sep = ";")
row_data <- read.csv("eCO2mix_RTE_En-cours-TR.csv", header = TRUE, sep = " ")
attach(row_data)
```

# Data summary
```{r}
# print the data summary
summary(row_data)
```


# Data preparation
```{r}

```

# Data visualization
```{r}
# convert date_heure column to date format
row_data$date_heure <- as.Date(row_data$date_heure, format = "%d/%m/%Y %H:%M")

# visualize dates distribution
hist(row_data$date_heure, breaks = 100, main = "Distribution des dates", xlab = "Date")

```


# Data visualization
```{r}
# load ggplot2 package
library(ggplot2)

# plot the data
ggplot(row_data, aes(x = date_heure, y = production_totale_mw, color = Filière)) + geom_line() + geom_point() + labs(title = "Production d'électricité par filière", x = "Année", y = "Production (GWh)")

```